pull_request_templates:
  - name: ğŸ› Bug Fix
    path: PULL_REQUEST_TEMPLATE/bug_fix.md
  - name: âœ¨ Feature Addition
    path: PULL_REQUEST_TEMPLATE/feature_addition.md
  - name: ğŸ“š Documentation Update
    path: PULL_REQUEST_TEMPLATE/docs_update.md
  - name: âš™ï¸ Setting/Environment Change
    path: PULL_REQUEST_TEMPLATE/setting_change.md
